#pragma once

#include "stdio.h"

#define DIRECTION_POSITIVE 1	//right,down
#define DIRECTION_DEFAULT 0    //using current direction of obj
#define DIRECTION_NEGATIVE -1	//left,up

#define BOARD_WIDTH 320	
#define BOARD_HEIGHT 43


#pragma region TEXTURE_PATHS

#define TEXTURES_DIR L"textures"
#define ENEMYSTEX_DIR L"\\enemy"


#define TEXTURE_PATH_SIMON TEXTURES_DIR "\\Simon.png"

#define TEXTURE_PATH_MAP1 TEXTURES_DIR "\\map1.png"

#define TEXTURE_PATH_TORCH TEXTURES_DIR  "\\Torch.png"



#define TEXTURE_PATH_FISHMAN TEXTURES_DIR ENEMYSTEX_DIR  "\\FishMan.png"
#define TEXTURE_PATH_EAGLE TEXTURES_DIR ENEMYSTEX_DIR  "\\Eagle.png"
#define TEXTURE_PATH_CANON TEXTURES_DIR ENEMYSTEX_DIR "\\Dragon_Canon.png"
#define TEXTURE_PATH_KNIGHT TEXTURES_DIR ENEMYSTEX_DIR "\\Black_knight.png"
#define TEXTURE_PATH_AXEMAN TEXTURES_DIR ENEMYSTEX_DIR "\\Axe_Man.png"
#define TEXTURE_PATH_GHOST TEXTURES_DIR ENEMYSTEX_DIR "\\Ghost.png"
#define TEXTURE_PATH_FLEAMAN TEXTURES_DIR ENEMYSTEX_DIR "\\Fleaman.png"
#define TEXTURE_PATH_LEOPARD TEXTURES_DIR ENEMYSTEX_DIR "\\Leopard.png"
#define TEXTURE_PATH_MEDUSA TEXTURES_DIR ENEMYSTEX_DIR "\\Medusa.png"
#define TEXTURE_PATH_RAVEN TEXTURES_DIR ENEMYSTEX_DIR "\\Raven.png"
#define TEXTURE_PATH_SKELETON TEXTURES_DIR ENEMYSTEX_DIR "\\Skeleton.png"
#define TEXTURE_PATH_BAT TEXTURES_DIR ENEMYSTEX_DIR "\\Vampire_bat.png"
#define TEXTURE_PATH_ZOMBIE TEXTURES_DIR ENEMYSTEX_DIR "\\Zombie.png"

#define TEXTURE_PATH_WHIP TEXTURES_DIR  "\\Whip.png"
#define TEXTURE_PATH_AXE TEXTURES_DIR  "\\Axe.png"

#define TEXTURE_PATH_TILESET1 TEXTURES_DIR  "\\tileset_map1.png"
#define TEXTURE_PATH_BLACKBOARD TEXTURES_DIR  "\\Blackboard.png"
#define TEXTURE_PATH_MISC TEXTURES_DIR "\\2.png"


#pragma endregion

#pragma region SIMON_ANIMATION_

#define SIMON_HEIGHT_ADJUST  6.0f // adjust simon y position when sitting or jumping, avoid overlaping .

// aniID  = objectID + index of sprite in spriteSheet
#define SIMON_ANI_IDLE 1000
#define SIMON_ANI_FALLING 1000

#define SIMON_ANI_WALKING_BEGIN 1001
#define SIMON_ANI_WALKING_END 1003

#define SIMON_ANI_JUMPING 1004
#define SIMON_ANI_DUCKING 1004


/**************ATTACKKING ANIMATION******************/

//Ani Duck Attack
#define SIMON_ANI_DUCKING_ATTACKING_BEGIN 1015
#define SIMON_ANI_DUCKING_ATTACKING_END 1017

//Ani Stand Attack
#define SIMON_ANI_STANDING_ATTACKING_BEGIN 1005
#define SIMON_ANI_STANDING_ATTACKING_END 1007

//Ani Climb down stairs Attack
#define SIMON_ANI_STAIR_DOWN_ATTACKING_BEGIN 1018
#define SIMON_ANI_STAIR_DOWN_ATTACKING_END 1020

//Ani Climb up stairs Attack
#define SIMON_ANI_STAIR_UP_ATTACKING_BEGIN 1021
#define SIMON_ANI_STAIR_UP_ATTACKING_END 1023

// Time Ani attack 
#define SIMON_TIME_ATTACKING_TRANS 120  //frame transition time when attacking

/*******************************************/

#define SIMON_ANI_HURTING 1008
#define SIMON_ANI_DEADTH 1024

#define SIMON_ANI_HIDE_FACE 1009


/*******NORMAL ON_STAIRS ANIMATION**********/

//Ani Climb down stairs
#define SIMON_ANI_STAIR_GO_DOWN_BEGIN 1010
#define SIMON_ANI_STAIR_GO_DOWN_END 1011

//Ani Climb down stairs
#define SIMON_ANI_STAIR_GO_UP_BEGIN 1012
#define SIMON_ANI_STAIR_GO_UP_END 1013

//Ani standing in stairs
#define SIMON_ANI_STAIR_STANDING_UP 1012
#define SIMON_ANI_STAIR_STANDING_DOWN 1010

/*******************************************/

//Ani Brick
#pragma endregion 

#pragma region ENEMIES_ANIMATION_
#define GHOST_ANI_BEGIN 1100
#define GHOST_ANI_END 1101

#define LEOPARD_ANI_IDLE 1110
#define LEOPARD_ANI_RUNING_BEGIN 1111
#define LEOPARD_ANI_RUNNING_END 1113

#define BAT_ANI_IDLE 1120
#define BAT_ANI_FLYING_BEGIN 1121
#define BAT_ANI_FLYING_END 1123

#define FISHMAN_ANI_ATTACKING 1130
#define FISHMAN_ANI_WALKING_BEGIN 1131
#define FISHMAN_ANI_WALKING_END 1132
#define FISHMAN_ANI_JUMPING 1133

#define AXEMAN_ANI_WALKING_BEGIN 1140
#define AXEMAN_ANI_WALKING_END 1141


#define KNIGHT_ANI_WALKING_BEGIN 1150
#define KNIGHT_ANI_WALKING_END 1153

#define ZOMBIE_ANI_BEGIN 1160
#define ZOMBIE_ANI_END 1161



#pragma endregion

#pragma region WEAPON_ANIMATION_

#define WHIP_ANI_ATTACKING_BEGIN 4000
#define WHIP_ANI_ATTACKING_END 4002

#define AXE_ANI_ATTACKING_BEGIN 4010
#define AXE_ANI_ATTACKING_END 4013	
#pragma endregion



#define TORCH_ANI_BEGIN 5000
#define TORCH_ANI_END 5001

    
#pragma region SIMON_PARAMETERS

#define SIMON_GRAVITY 0.0018f 

#define SIMON_WALKING_SPEED 0.1f
#define SIMON_JUMPING_WALKING_SPEED 0.2f

#define SIMON_SPEED_ONSTAIR 0.045f 
#define SIMON_ACCEL_WALK_X	0.00025f
#define SIMON_JUMP_SPEED_Y 0.4f
#define SIMON_JUMP_HURT_SPEED_Y 0.40f



#define SIMON_DEFAULT_HEALTH 16
#define SIMON_DEFAULT_HEARTCOLLECT 5
#define SIMON_DEFAULT_SCORE 0
#define SIMON_DEFAULT_LIVES 3
#pragma endregion


/*******GAME OBJECT ID**********/
enum class Type {

	//MAPTILES SET
	TILESET_LEVEL1 = 0,
	BLACKBOARD = 900,

	SIMON = 1000,


	// Enemy
	GHOST = 1100,
	LEOPARD = 1110,
	BAT = 1120,
	FISHMAN = 1130,
	AXEMAN = 1140,
	KNIGHT = 1150,
	ZOMBIE = 1160,
	SKELETON = 1170,
	CANON = 1180,
	MEDUSA_HEAD = 1190,
	FLEAMAN = 1200,
	RAVEN = 1210,
	EAGLE = 1220,



	//BOSS
	PHANTOMBAT = 2100,
	MEDUSA = 2110,
	MUMMYMAN = 2120,
	FRANKENSTEIN = 2130,
	DEATH = 2140,
	DRACULAR = 2150,
	COOKIE_MOSTER = 2160,


	//BRICK
	BRICK = 3000,


	//WEAPON
	WHIP = 4000,
	AXE = 4010,



	TORCH = 5000


};

enum class sType {
	IDLE = 100,
	JUMPING = 101,
	DUCKING = 102,
	WALKING = 103,
	ONSTAIRS = 104,
	WALKING_ONSTAIRS = 105,
	DIE = 106,

	FALLING = 107,
	HURTING = 108,
	ATTACKING = 109

};
