#pragma once

#include "stdio.h"

#define DIRECTION_POSITIVE 1	//right,down
#define DIRECTION_DEFAULT 0    //using current direction of obj
#define DIRECTION_NEGATIVE -1	//left,up

#define GAME_WIDTH	640
#define GAME_HEIGHT	480
#define FRAME_RATE 30
#define FPS	60
#define MAX_TIME_PER_FRAME	1000 / FPS
#define FULLSCREEN false 
#define BOARD_WIDTH 640 
#define BOARD_HEIGHT 98

#define GAME_MENU_STATE			-1
#define GAME_INTRO_SCENE		0
#define GAME_LOSE_LAYER			4
#define	GAME_PLAY_STATE_ONE		1
#define GAME_PLAY_STATE_TWO		2


#define TAG_CHECK_POINT		21
#define TAG_CHECK_STAIR		23


#define IS_DEBUG_RENDER_BBOX isDebug_RenderBBox


#pragma region TEXTURE_PATHS

#define TEXTURES_DIR L"textures"
#define ENEMYSTEX_DIR L"\\enemy"
#define GROUND_DIR L"\\Ground"
#define UI_DIR L"\\UI"
#define SIMON_DIR L"\\Simon"
#define WEAPONS_DIR L"\\Weapons"


#define TEXTURE_PATH_SIMON TEXTURES_DIR "\\simon.png"
#define TEXTURE_PATH_SIMON_EDIT TEXTURES_DIR SIMON_DIR "\\Simon_ver_editted.png"
#define TEXTURE_PATH_WHIP_EDIT TEXTURES_DIR WEAPONS_DIR "\\WHIP.png"

#define TEXTURE_PATH_MAP1 TEXTURES_DIR "\\map1.png"

#define TEXTURE_PATH_LARGE_CANDLE TEXTURES_DIR GROUND_DIR  "\\0.png"
#define TEXTURE_PATH_GROUND TEXTURES_DIR GROUND_DIR  "\\2.png"
#define TEXTURE_PATH_GROUND_TWO TEXTURES_DIR GROUND_DIR  "\\brick.png"
#define TEXTURE_PATH_GROUND_THREE TEXTURES_DIR GROUND_DIR  "\\ground.png"
#define TEXTURE_PATH_GROUND_CHANGE_STATE TEXTURES_DIR GROUND_DIR  "\\2.png"
#define TEXTURE_PATH_STAIR TEXTURES_DIR GROUND_DIR  "\\3.png"
#define TEXTURE_PATH_STAIR_TWO TEXTURES_DIR GROUND_DIR  "\\stair.png"
#define TEXTURE_PATH_TOP_STAIR TEXTURES_DIR GROUND_DIR  "\\top_stair.png"
#define TEXTURE_PATH_STAIR_THREE TEXTURES_DIR GROUND_DIR  "\\3_.png"

#define TEXTURE_PATH_STAIR_TOP TEXTURES_DIR GROUND_DIR  "\\4.png"
#define TEXTURE_PATH_STAIR_TOP_TWO TEXTURES_DIR GROUND_DIR  "\\4_.png"
#define TEXTURE_PATH_SMALL_CANDLE TEXTURES_DIR GROUND_DIR  "\\1.png"
#define TEXTURE_PATH_STAIR_TOP_THREE TEXTURES_DIR GROUND_DIR  "\\stair_top.png"
#define TEXTURE_PATH_STAIR_BOTTOM TEXTURES_DIR GROUND_DIR  "\\stair_bottom.png"
#define TEXTURE_PATH_CHECK_STAIR TEXTURES_DIR GROUND_DIR  "\\13.png"
#define TEXTURE_PATH_DOOR TEXTURES_DIR GROUND_DIR  "\\Door.png"
#define TEXTURE_PATH_SMALL_DOOR TEXTURES_DIR GROUND_DIR  "\\10.png"
#define TEXTURE_PATH_CHECK_POINT TEXTURES_DIR GROUND_DIR  "\\wall.png"

#define TEXTURE_PATH_FISHMAN TEXTURES_DIR ENEMYSTEX_DIR  "\\FishMan.png"
#define TEXTURE_PATH_EAGLE TEXTURES_DIR ENEMYSTEX_DIR  "\\Eagle.png"
#define TEXTURE_PATH_CANON TEXTURES_DIR ENEMYSTEX_DIR "\\Dragon_Canon.png"
#define TEXTURE_PATH_KNIGHT TEXTURES_DIR ENEMYSTEX_DIR "\\Black_knight.png"
#define TEXTURE_PATH_AXEMAN TEXTURES_DIR ENEMYSTEX_DIR "\\Axe_Man.png"
#define TEXTURE_PATH_GHOST TEXTURES_DIR ENEMYSTEX_DIR "\\Ghost.png"
#define TEXTURE_PATH_FLEAMAN TEXTURES_DIR ENEMYSTEX_DIR "\\Fleaman.png"
#define TEXTURE_PATH_LEOPARD TEXTURES_DIR ENEMYSTEX_DIR "\\Leopard.png"
#define TEXTURE_PATH_MEDUSA TEXTURES_DIR ENEMYSTEX_DIR "\\Medusa.png"
#define TEXTURE_PATH_RAVEN TEXTURES_DIR ENEMYSTEX_DIR "\\Raven.png"
#define TEXTURE_PATH_SKELETON TEXTURES_DIR ENEMYSTEX_DIR "\\Skeleton.png"
#define TEXTURE_PATH_BAT TEXTURES_DIR ENEMYSTEX_DIR "\\Vampire_bat.png"
#define TEXTURE_PATH_ZOMBIE TEXTURES_DIR ENEMYSTEX_DIR "\\Zombie.png"

#define TEXTURE_PATH_BLACK TEXTURES_DIR UI_DIR "\\black.png"
#define TEXTURE_PATH_SIMONHP TEXTURES_DIR UI_DIR "\\HP.png"
#define TEXTURE_PATH_ENEMYHP TEXTURES_DIR UI_DIR "\\EnemyHP.png"
#define TEXTURE_PATH_NOHP TEXTURES_DIR UI_DIR "\\NoHP.png"
#define TEXTURE_PATH_HEART TEXTURES_DIR UI_DIR "\\heart.png"
#define TEXTURE_PATH_AXEICON TEXTURES_DIR UI_DIR "\\AXE.png"
#define TEXTURE_PATH_HOLYWATERICON TEXTURES_DIR UI_DIR "\\HOLY_WATER.png"
#define TEXTURE_PATH_CROSS TEXTURES_DIR UI_DIR "\\CROSS.png"
#define TEXTURE_PATH_KNIFE TEXTURES_DIR UI_DIR "\\KNIFE.png"
#define TEXTURE_PATH_STOPWATCH TEXTURES_DIR UI_DIR "\\STOP_WATCH.png"
#define TEXTURE_PATH_DOUBLESHOTUI TEXTURES_DIR UI_DIR "\\DOUBLE_SHOT_UI.png"
#define TEXTURE_PATH_TRIPLESHOTUI TEXTURES_DIR UI_DIR "\\TRIPLE_SHOT_UI.png"

#define TEXTURE_PATH_WHIP TEXTURES_DIR  "\\Whip.png"

#define TEXTURE_PATH_TILESET1 TEXTURES_DIR  "\\tileset_map1.png"
#define TEXTURE_PATH_BLACKBOARD TEXTURES_DIR  "\\blackboard.png"
#define TEXTURE_PATH_MISC TEXTURES_DIR "\\2.png"


#pragma endregion

#pragma region SIMON_ANIMATION_

#define SIMON_HEIGHT_ADJUST  16.0f // adjust simon y position when sitting or jumping, avoid overlaping .

// aniID  = objectID + index of sprite in spriteSheet
#define SIMON_ANI_IDLE 1000
#define SIMON_ANI_FALLING 1000

#define SIMON_ANI_WALKING_BEGIN 1001
#define SIMON_ANI_WALKING_END 1003

#define SIMON_ANI_JUMPING 1004
#define SIMON_ANI_DUCKING 1004


/**************ATTACKKING ANIMATION******************/

//Ani Duck Attack
#define SIMON_ANI_DUCKING_ATTACKING_BEGIN 1015
#define SIMON_ANI_DUCKING_ATTACKING_END 1017

//Ani Stand Attack
#define SIMON_ANI_STANDING_ATTACKING_BEGIN 1005
#define SIMON_ANI_STANDING_ATTACKING_END 1007

//Ani Climb down stairs Attack
#define SIMON_ANI_STAIR_DOWN_ATTACKING_BEGIN 1018
#define SIMON_ANI_STAIR_DOWN_ATTACKING_END 1020

//Ani Climb up stairs Attack
#define SIMON_ANI_STAIR_UP_ATTACKING_BEGIN 1021
#define SIMON_ANI_STAIR_UP_ATTACKING_END 1023

// Time Ani attack 
#define SIMON_TIME_ATTACKING_TRANS 120  //frame transition time when attacking

/*******************************************/

#define SIMON_ANI_HURTING 1008

#define SIMON_ANI_HIDE_FACE 1009


/*******NORMAL ON_STAIRS ANIMATION**********/

//Ani Climb down stairs
#define SIMON_ANI_STAIR_GO_DOWN_BEGIN 1010
#define SIMON_ANI_STAIR_GO_DOWN_END 1011

//Ani Climb down stairs
#define SIMON_ANI_STAIR_GO_UP_BEGIN 1012
#define SIMON_ANI_STAIR_GO_UP_END 1013

//Ani standing in stairs
#define SIMON_ANI_STAIR_STANDING_UP 1012
#define SIMON_ANI_STAIR_STANDING_DOWN 1010

/*******************************************/

//Ani Brick
#pragma endregion 

#pragma region ENEMIES_ANIMATION_
#define GHOST_ANI_BEGIN 1100
#define GHOST_ANI_END 1101

#define LEOPARD_ANI_IDLE 1110
#define LEOPARD_ANI_RUNING_BEGIN 1111
#define LEOPARD_ANI_RUNNING_END 1113

#define BAT_ANI_IDLE 1120
#define BAT_ANI_FLYING_BEGIN 1121
#define BAT_ANI_FLYING_END 1123

#define FISHMAN_ANI_ATTACKING 1130
#define FISHMAN_ANI_WALKING_BEGIN 1131
#define FISHMAN_ANI_WALKING_END 1132
#define FISHMAN_ANI_JUMPING 1133

#define AXEMAN_ANI_WALKING_BEGIN 1140
#define AXEMAN_ANI_WALKING_END 1141


#define KNIGHT_ANI_WALKING_BEGIN 1150
#define KNIGHT_ANI_WALKING_END 1153

#define ZOMBIE_ANI_BEGIN 1160
#define ZOMBIE_ANI_END 1161

#define LARGE_CANDLE_ANI_BEGIN 5000
#define LARGE_CANDLE_ANI_END 5001

#define SMALL_CANDLE_ANI_BEGIN 5010
#define SMALL_CANDLE_ANI_END 5011

#define DOOR_ANI_BEGIN 5020
#define DOOR_ANI_END 5021

#pragma endregion

#pragma region WEAPON_ANIMATION_
#define WHIP_ANI_ATTACKING_BEGIN 4000
#define WHIP_ANI_ATTACKING_END 4002
#pragma endregion


/*******GAME OBJECT ID**********/
enum class Type {
	//object ui
	BLACK_UI = 1,
	SIMON_HP_UI = 2,
	ENEMY_HP_UI = 3,
	NO_HP_UI = 4,
	HEART_UI = 5,
	AXE_ICON_UI = 6,
	HOLY_WATER_ICON_UI = 7, 
	CROSS_UI = 8,
	KNIFE_UI = 9,
	STOP_WATCH_UI = 10, 
	DOUBLE_SHOT_UI = 11,
	TRIPLE_SHOT_UI = 12,


	// object nền

	BRICK_MODEL_1 = 22,
	BRICK_MODEL_2 = 23,
	BRICK_MODEL_3 = 24,
	BRICK_TRANSPARENT = 25,
	GATE = 26,
	BRICK_MODEL_3_3_32 = 27,
	BRICK_MODEL_3_4_32 = 28,


	// object
	TORCH = 41,
	OBJECT_HIDDEN = 42,
	CANDLE = 43,
	STAIR = 44,
	/*	STAIR_UP = 45,
		STAIR_EXIT = 46,*/
	STAIR_BOTTOM = 47,
	STAIR_TOP = 48,


	//MAPTILES SET
	TILESET_LEVEL1 = 0,
	BLACKBOARD = 900,

	SIMON = 1000,
	SIMON_EDIT = 2000,

	// Enemy
	GHOST = 1100,
	LEOPARD = 1110,
	BAT = 1120,
	FISHMAN = 1130,
	AXEMAN = 1140,
	KNIGHT = 1150,
	ZOMBIE = 1160,
	SKELETON = 1170,
	CANON = 1180,
	MEDUSA_HEAD = 1190,
	FLEAMAN = 1200,
	RAVEN = 1210,
	EAGLE = 1220,



	//BOSS
	PHANTOMBAT = 2100,
	MEDUSA = 2110,
	MUMMYMAN = 2120,
	FRANKENSTEIN = 2130,
	DEATH = 2140,
	DRACULAR = 2150,
	COOKIE_MOSTER = 2160,


	//BRICK
	BRICK = 3000,


	//WEAPON
	WHIP = 4000,
	WHIP_EDIT = 4100,

	//GROUND
	LARGE_CANDLE = 5000,
	SMALL_CANDLE = 5010,
	DOOR = 5020,
	CHECK_POINT = 5030

};

enum class sType {
	SIMON_STATE_IDLE = 100,
	SIMON_STATE_JUMPING = 101,
	SIMON_STATE_DUCKING = 102,
	SIMON_STATE_WALKING = 103,
	SIMON_STATE_ONSTAIRS = 104,
	SIMON_STATE_WALKING_ONSTAIRS = 105,
	SIMON_STATE_DIE = 106,

	SIMON_STATE_FALLING = 107,
	SIMON_STATE_HURTING = 108,

	DEFAULT_STATE = 0,

};

